# component=shipping
# source common.sh
# maven_app_setup

# print_head Install mysql and SQL files 
# dnf install mysql -y  &>>$log_file 
# exit_status_print $?


# for file in schema app-user master-data; do 
#     print_head Load $file
#     mysql -h mysql-{{ env }}.santoshpawar.site -uroot -pRoboShop@1 < /app/db/$file.sql  &>>$log_file
# done

- name : Load Maven
  ansible.builtin.include_role:
    name: common
    tasks_from: maven

- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name : Load Schema
  ansible.builtin.shell: mysql -h mysql-{{ env }}.santoshpawar.site -uroot -pRoboShop@1 < /app/db/schema.sql
- name : Load User Creation
  ansible.builtin.shell: mysql -h mysql-{{ env }}.santoshpawar.site -uroot -pRoboShop@1 < /app/db/app-user.sql
- name : Load Master data
  ansible.builtin.shell: mysql -h mysql-{{ env }}.santoshpawar.site -uroot -pRoboShop@1 < /app/db/master-data.sql