# component=dispatch
# source common.sh

# print_head Install Golang
# dnf install golang -y &>>$log_file
# useradd roboshop &>>$log_file
# cp -r dispatch.service /etc/systemd/system/dispatch.service  &>>$log_file
# exit_status_print $?

# print_head Clean up /app
# rm -rf /app
# mkdir /app 
# curl -L -o /tmp/dispatch.zip https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip  &>>$log_file
# cd /app 
# exit_status_print $?

# print_head Unzip artifact
# unzip /tmp/dispatch.zip  &>>$log_file
# cd /app 

# print_head Build the App
# go mod init dispatch  &>>$log_file
# go get  &>>$log_file
# go build &>>$log_file
# exit_status_print $?

# systemd_setup

- name: Install Golang
  ansible.builtin.dnf:
    name: golang
    state: installed

- name : Load nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: artifact_download

- name: Build the App
  ansible.builtin.shell: go mod init dispatch ; go get ; go build   
  args:
    chdir: /app

- name : Include systemd_setup
  ansible.builtin.include_role:
    tasks_from: systemd_setup