# python_app_setup() {
#     print_head Install Python Packages
#     dnf install python3 gcc python3-devel -y  &>>$log_file
#     exit_status_print $?
#     artifact_download 
#     cd /app 
#     print_head Install Python Dependencies
#     pip3 install -r requirements.txt  &>>$log_file
#     exit_status_print $?
#     systemd_setup
# }

- name : Install Python
  ansible.builtin.dnf: 
    name: 
      - python3
      - gcc
      - python3-devel
    state: installed  

- name : Include artifact_download
  ansible.builtin.include_tasks:
    file: artifact_download.yml

- name : Install Python dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app
    
- name : Include systemd_setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml