# systemd_setup () {
#     print_head Copy SystemD Service Files
#     cp -r $pwd/$component.service /etc/systemd/system/$component.service &>>$log_file 
#     exit_status_print $?
#     print_head Start Service 
#     systemctl daemon-reload &>>$log_file 
#     systemctl enable $component &>>$log_file
#     systemctl restart $component &>>$log_file
#     exit_status_print $?
# }


- name: Copy Systemd service file
  ansible.builtin.template:
    src: "{{ component_name }}.service"
    dest: /etc/systemd/system/{{ component_name }}.service

- name : Start Service
  ansible.builtin.systemd_service:
    name: "{{ component_name }}"
    state : restarted 
    enabled: yes
    daemon_reload: yes 